import {
  StateGraph,
  StateSchema,
  MessagesValue,
  ReducedValue,
  type CompiledGraph,
  START,
  END,
  Annotation,
} from "@langchain/langgraph";
import { z } from "zod";
import type { GraphNode } from "@langchain/langgraph";
import { mistralModel, cohereModel, giminiModel } from "./model.service.js";
import { createAgent, providerStrategy,HumanMessage } from "langchain";

// const State = new StateSchema({
//     problem: z.string().default(""),
//     solution_1: z.string().default(""),
//     solution_2: z.string().default(""),
//     judge: z.object({
//         solution_1_score: z.number().default(0),
//         solution_2_score: z.number().default(0),
//         solution_1_reasoning: z.string().default(""),
//         solution_2_reasoning: z.string().default(""),
//     })
// })

//  plain TypeScript interface (No Zod Object here)
interface JudgeEvaluation {
    solution_1_score: number;
    solution_2_score: number;
    solution_1_reasoning: string;
    solution_2_reasoning: string;
}

// 2. LangGraph v0.2+ standard Annotation system 
export const State = Annotation.Root({
    problem: Annotation<string>({
        reducer: (current, next) => next,
        default: () => ""
    }),
    solution_1: Annotation<string>({
        reducer: (current, next) => next,
        default: () => ""
    }),
    solution_2: Annotation<string>({
        reducer: (current, next) => next,
        default: () => ""
    }),
    // Complex object ko bina Zod ke handle karo:
    judge: Annotation<JudgeEvaluation>({
        reducer: (current, next) => next,
        default: () => ({
            solution_1_score: 0,
            solution_2_score: 0,
            solution_1_reasoning: "",
            solution_2_reasoning: "",
        })
    })
});


const solution_node: GraphNode<typeof State> = async (state) => {
  console.log(state.problem);

  const [mistralResponse, cohereResponse] = await Promise.all([
        mistralModel.invoke(state.problem),
        cohereModel.invoke(state.problem)
    ])

    return {
        solution_1: mistralResponse.text,
        solution_2: cohereResponse.text,
    }
};

const judge_node: GraphNode<typeof State> = async (state) => {
  const { problem, solution_1, solution_2 } = state;
    console.log("Running judge_node...");

    const evaluationSchema = z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_reasoning: z.string(),
        solution_2_reasoning: z.string(),
    });

    const structuredGemini = giminiModel.withStructuredOutput(evaluationSchema, {
        name: "evaluator",
        method: "functionCalling" 
    });

    const result = await structuredGemini.invoke(
        `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.
        
        Problem: ${problem}
        Solution 1: ${solution_1}
        Solution 2: ${solution_2}
        
        Please evaluate the solutions and provide scores and reasoning.`
    );

    return {
        judge: result
    };
};

export default async (problem: string) => {
  const graph = new StateGraph(State)
    .addNode("solution_node", solution_node)
    .addNode("judge_node", judge_node)
    .addEdge(START, "solution_node")
    .addEdge("solution_node", "judge_node")
    .addEdge("judge_node", END)
    .compile();

  const result = await graph.invoke({
    problem :problem
  })

  // console.log("fetching result....");
  console.log(result);

  return result
};
